apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-chart.fullname" . }}
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /otusapp/adyakonov($|/)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "hello-chart.fullname" . }}
              port:
                number: {{ .Values.service.port }}