{
 "title": "My dashboard App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum by (le)(rate(app_request_latency_seconds_bucket{exported_endpoint=\"/user\"}[2m])))"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum by (le)(rate(app_request_latency_seconds_bucket{exported_endpoint=\"/user\"}[2m])))"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by (le)(rate(app_request_latency_seconds_bucket{exported_endpoint=\"/user\"}[2m])))"
    }
   ]
  },
  {
   "title": "Latency max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(1,sum by (le)(rate(app_request_latency_seconds_bucket{exported_endpoint=\"/user\"}[2m])))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{exported_endpoint=\"/user\"}[2m]))"
    }
   ]
  },
  {
   "title": "Error Rate Count 404",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(app_request_count_total{http_status=~\"4.+\"}[2m])"
    }
   ]
  }
 ]
}