{
 "title": "My dashboard Nginx Ingress Controller",
 "time": { "from": "2021-08-15T08:34:09.809Z", "to": "2021-08-15T09:05:43.419Z" },
 "panels": [
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_ingress_upstream_latency_seconds_sum[2m])) / sum(rate(nginx_ingress_controller_ingress_upstream_latency_seconds_count[2m])) * 1000"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "HTTP Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"4.+\"}[1m]))/sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count[1m])) * 100"
    }
   ]
  }
 ]
}