---
replicaCount: 1

image: adyakonov/auth-service:latest

fullnameOverride: "auth"

service:
  type: NodePort
  port: 8000

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"
